# Generated by Django 6.0 on 2026-08-17 13:14

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('tipo', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_correlativo', models.CharField(max_length=100, unique=True)),
                ('fecha_toma', models.DateField()),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('cantidad_muestras', models.IntegerField()),
                ('numero_fragmentos', models.IntegerField()),
                ('tincion_rutina', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnicas_especiales', models.TextField(blank=True, null=True)),
                ('alerta_chat_patologo', models.BooleanField(default=False)),
                ('alerta_chat_laboratorio', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_informe', models.FileField(blank=True, null=True, upload_to='informes/')),
                ('galeria_imagenes', models.JSONField(blank=True, null=True)),
                ('resultado_critico', models.BooleanField(default=False)),
                ('informe_cerrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalExamen',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_correlativo', models.CharField(db_index=True, max_length=100)),
                ('fecha_toma', models.DateField()),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('cantidad_muestras', models.IntegerField()),
                ('numero_fragmentos', models.IntegerField()),
                ('tincion_rutina', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnicas_especiales', models.TextField(blank=True, null=True)),
                ('alerta_chat_patologo', models.BooleanField(default=False)),
                ('alerta_chat_laboratorio', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_informe', models.TextField(blank=True, max_length=100, null=True)),
                ('galeria_imagenes', models.JSONField(blank=True, null=True)),
                ('resultado_critico', models.BooleanField(default=False)),
                ('informe_cerrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical examen',
                'verbose_name_plural': 'historical examens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaPatologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Gastritis Crónica Antral Leve', max_length=150)),
                ('texto_predefinido', models.TextField(help_text='Texto diagnóstico que se inyectará en el informe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla Personal de Patólogo',
                'verbose_name_plural': 'Plantillas Personales de Patólogos',
            },
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plantilla_preinforme', models.TextField(blank=True, help_text='Escriba la estructura predeterminada que verá el patólogo al redactar este examen.', null=True, verbose_name='Plantilla de Pre-Informe')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
