# Generated by Django 6.0 on 2026-08-17 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biopsias', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examen',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.laboratorio'),
        ),
        migrations.AddField(
            model_name='examen',
            name='patologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='biopsias.examen'),
        ),
        migrations.AddField(
            model_name='historicalexamen',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexamen',
            name='laboratorio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.laboratorio'),
        ),
        migrations.AddField(
            model_name='historicalexamen',
            name='patologo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexamen',
            name='medico_solicitante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biopsias.medico'),
        ),
        migrations.AddField(
            model_name='examen',
            name='medico_solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biopsias.medico'),
        ),
        migrations.AddField(
            model_name='historicalexamen',
            name='paciente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biopsias.paciente'),
        ),
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='biopsias.paciente'),
        ),
        migrations.AddField(
            model_name='plantillapatologo',
            name='patologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_personales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillapatologo',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_patologo', to='biopsias.tipoexamen'),
        ),
        migrations.AddField(
            model_name='historicalexamen',
            name='tipo_examen',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biopsias.tipoexamen'),
        ),
        migrations.AddField(
            model_name='examen',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biopsias.tipoexamen'),
        ),
    ]
