# Generated by Django 6.0 on 2026-08-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='tiene_mensaje_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
