# Generated by Django 6.0 on 2026-08-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
