# Generated by Django 6.0 on 2026-08-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0003_examen_tiene_mensaje_pendiente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='tiene_mensaje_pendiente',
            new_name='alerta_chat_laboratorio',
        ),
        migrations.AddField(
            model_name='examen',
            name='alerta_chat_patologo',
            field=models.BooleanField(default=False),
        ),
    ]
