# Generated by Django 6.0 on 2026-08-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0003_medico_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_firmado',
            field=models.FileField(blank=True, help_text='PDF firmado Ley 21.719', null=True, upload_to='consentimientos/'),
        ),
    ]
