# Generated by Django 6.0 on 2026-08-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0004_rename_tiene_mensaje_pendiente_examen_alerta_chat_laboratorio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoexamen',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tipoexamen',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tipoexamen',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoexamen',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoexamen',
            name='plantilla_preinforme',
            field=models.TextField(blank=True, help_text='Escriba la estructura predeterminada que verá el patólogo al redactar este examen.', null=True, verbose_name='Plantilla de Pre-Informe'),
        ),
        migrations.AlterField(
            model_name='tipoexamen',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
