# Generated by Django 6.0 on 2026-08-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0004_paciente_consentimiento_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre_social',
            field=models.CharField(blank=True, help_text='Circular N° 21 Minsal', max_length=150, null=True),
        ),
    ]
