# Generated by Django 6.1 on 2026-08-16 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0005_remove_tipoexamen_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='examen',
            name='paciente_nombre',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='paciente_rut',
        ),
        migrations.AddField(
            model_name='examen',
            name='informe_cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examen',
            name='resultado_critico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='biopsias.paciente'),
            preserve_default=False,
        ),
    ]
