# Generated by Django 6.1 on 2026-08-16 04:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0006_paciente_remove_examen_paciente_nombre_and_more'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExamen',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_correlativo', models.CharField(db_index=True, max_length=100)),
                ('fecha_toma', models.DateField()),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('cantidad_muestras', models.IntegerField()),
                ('numero_fragmentos', models.IntegerField()),
                ('tincion_rutina', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnicas_especiales', models.TextField(blank=True, null=True)),
                ('alerta_chat_patologo', models.BooleanField(default=False)),
                ('alerta_chat_laboratorio', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_informe', models.TextField(blank=True, max_length=100, null=True)),
                ('galeria_imagenes', models.JSONField(blank=True, null=True)),
                ('resultado_critico', models.BooleanField(default=False)),
                ('informe_cerrado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='usuarios.laboratorio')),
                ('medico_solicitante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biopsias.medico')),
                ('paciente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biopsias.paciente')),
                ('patologo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_examen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='biopsias.tipoexamen')),
            ],
            options={
                'verbose_name': 'historical examen',
                'verbose_name_plural': 'historical examens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
