# Generated by Django 6.1 on 2026-08-16 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biopsias', '0007_historicalexamen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaPatologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Gastritis Crónica Antral Leve', max_length=150)),
                ('texto_predefinido', models.TextField(help_text='Texto diagnóstico que se inyectará en el informe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_personales', to=settings.AUTH_USER_MODEL)),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_patologo', to='biopsias.tipoexamen')),
            ],
            options={
                'verbose_name': 'Plantilla Personal de Patólogo',
                'verbose_name_plural': 'Plantillas Personales de Patólogos',
            },
        ),
    ]
