# Generated by Django 6.1 on 2026-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firma',
            field=models.ImageField(blank=True, help_text='Imagen de la firma hológrafa transparente', null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_firma',
            field=models.CharField(blank=True, help_text='PIN de 4-6 dígitos para autorizar el cierre del informe', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registro_medico',
            field=models.CharField(blank=True, help_text='N° de Registro Nacional de Prestadores de Salud', max_length=100, null=True),
        ),
    ]
